# @package _global_.model

model_name: autoencoder

# Architecture
input_dim: 333  # num_species
hidden_dims: [160, 80]
latent_dim: 14

# Hyperparameters
lr: 1.0e-3
lr_decay: 0.5
lr_decay_patience: 12
betas: [0.99, 0.999]
weight_decay: 1.0e-4
power_weight: 20
conservation_weight: 100
batch_size: 65536  # 8 * 8192
stagnant_epoch_patience: 20
gradient_clipping: 2.0
dropout_decay_patience: 10
dropout_reduction_factor: 0.05
dropout: 0.3
noise: 0.1
shuffle_chunk_size: 1.0

# Paths
save_model: true
pretrained_model_path: ${working_path}/weights/autoencoder.pth
save_model_path: ${working_path}/weights/autoencoder.pth
latents_minmax_path: ${working_path}/utils/latents_minmax.npy
