# @package _global_.model

model_name: emulator

# Architecture
input_dim: 18  # num_phys (4) + latent_dim (14)
output_dim: 14  # latent_dim
hidden_dim: 180
latent_dim: 14
window_size: 240

# Hyperparameters
lr: 1.0e-3
lr_decay: 0.5
lr_decay_patience: 5
betas: [0.9, 0.995]
weight_decay: 1.0e-3
power_weight: 20
conservation_weight: 500
batch_size: 3072  # 6 * 512
stagnant_epoch_patience: 20
gradient_clipping: 1.0
dropout_decay_patience: 3
dropout_reduction_factor: 0.05
dropout: 0.0
shuffle: true
shuffle_chunk_size: 1.0

# Paths
save_model: false
pretrained_model_path: ${working_path}/weights/mlp.pth
save_model_path: ${working_path}/weights/mlp.pth
