# @package _global_.dataset

dataset_path: ${working_path}/outputs/temp_data/grav_collapse_clean.h5

physical_parameter_ranges:
  Density: [68481, 1284211415]
  Radfield: [1.0e-4, 26]
  Av: [0.1, 6914]
  gasTemp: [13, 133]

# Abundances clipping range
abundances_clipping:
  lower: 1.0e-20
  upper: 1.0

metadata: [Index, Model, Time]
parameters: [Density, Radfield, Av, gasTemp]

initial_abundances_path: ${working_path}/utils/initial_abundances.npy
stoichiometric_matrix_path: ${working_path}/utils/stoichiometric_matrix.npy
species_path: ${working_path}/utils/species.txt

# Preprocessing parameters
preprocessing:
  input_path: ${working_path}/data/gravitational_collapse.h5
  output_path: ${working_path}/outputs/temp_data/grav_collapse_clean.h5
  input_key: df
  columns_to_drop: [dustTemp, dstep, zeta, SURFACE, BULK]
  train_split: 0.75
  seed: 42
  min_radfield: 1.0e-4
